-- Find the number of customers from each country

SELECT country,
    COUNT(*) as total_customers
FROM customers
group by country;

-- Find the average customer score for each country

SELECT country,
    AVG(score) as avg_score
FROM customers
GROUP BY country;

-- Find the total sales generated by each customer

SELECT customer_id, 
    SUM(sales) as total_sales
FROM orders
GROUP BY customer_id;

-- Find the highest customer score for each country

SELECT country,
    MAX(score) as max_score
FROM customers
GROUP BY country;

--Find the minimum customer score for each country

SELECT country,
    MIN(score) as min_score
FROM customers
GROUP BY country;


-- Find the total sales generated for each customer on each order date

SELECT customer_id, order_date, 
    SUM(sales) as total_sales
FROM orders
GROUP BY customer_id, order_date; 